sudo: false
language: Python
services:
  - docker

git:
    depth: 100500

env:
    matrix:
      - OS=fedora DIST=31

script:
 - ls -al .
 - pwd
 - wget https://tkn.me/tmp/python2-gevent-1.3.6-5.fc31.x86_64.rpm
 - wget https://tkn.me/tmp/python2-gevent-debuginfo-1.3.6-5.fc31.x86_64.rpm
 - wget https://tkn.me/tmp/python-gevent-1.3.6-5.fc31.src.rpm
 - wget https://tkn.me/tmp/python-gevent-debugsource-1.3.6-5.fc31.x86_64.rpm
 - ls -al *fc31*.rpm

deploy:
  # Deploy packages to PackageCloud
  provider: packagecloud
  username: packpack
  repository: backports
  token: ${PACKAGECLOUD_TOKEN}
  dist: ${OS}/${DIST}
  package_glob: '*.rpm'
  skip_cleanup: true
  on:
    all_branches: true
    condition: -n "${OS}" && -n "${DIST}" && -z "${ARCH}" && -n "${PACKAGECLOUD_TOKEN}"
